### ISSUE TITLE
grpc / gombile example, usng html5

### ISSUE THREAD

**Issue by joeblew99** [kenshaw/go-jakarta#1]
Very nice - thanks

What about if you have a html5 based UI?
You can use protocol buffers in web clients.
But how to use the underlying AAR that the gomobile code produces ?

I have seen a few questions and semi answers about this.
So, you you have any ideas about how to do this i would love to try it out on this code

**Comment by kenshaw** [comment]
The AAR package built by gomobile contains both native and Java code. The code is exposed through Java classes. You use it in the same way as any other Java code, through an `import` statement. If you're not sure of the names of the classes contained in the AAR, please have a look at https://github.com/knq/gop -- a tool that I built specifically to dump the contents of AAR/JAR/ZIP/etc files so that I could see the declared interfaces in the Java `.class` files contained inside. If you want to dump the contents of AAR files, you need to have the dex2jar util installed somewhere on your system.

**Comment by joeblew99** [comment]
thats a huge help. thank you.

i plan to use a json rpc style API in the golang code. 
So then i guess this is exposed as java code as you mentioned IF i compile with the "bind" ?
SO then i canowrite a cordova plugin to call the java, which calls the go ?

just checking my understanding of the flow with you..

**Comment by kenshaw** [comment]
I don't really have any experience with Cordova, but yes I believe that would be the correct implementation path.

**Comment by joeblew99** [comment]
thankyou. will try out some code now.
